# Generated by Django 5.2.16 on 2026-08-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prefix_name',
            field=models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว'), ('นาง', 'นาง')], default='นาย', max_length=10),
        ),
    ]
